# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yolo_command_setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 131)
        self.train_command_label = QtWidgets.QLabel(Form)
        self.train_command_label.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.train_command_label.setObjectName("train_command_label")
        self.train_command_textEdit = QtWidgets.QTextEdit(Form)
        self.train_command_textEdit.setGeometry(QtCore.QRect(90, 20, 291, 41))
        self.train_command_textEdit.setObjectName("train_command_textEdit")
        self.confirm_pushButton = QtWidgets.QPushButton(Form)
        self.confirm_pushButton.setGeometry(QtCore.QRect(70, 80, 75, 23))
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(Form)
        self.cancel_pushButton.setGeometry(QtCore.QRect(250, 80, 75, 23))
        self.cancel_pushButton.setObjectName("cancel_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "yolo训练命令设置"))
        self.train_command_label.setText(_translate("Form", "训练命令："))
        self.confirm_pushButton.setText(_translate("Form", "确定"))
        self.cancel_pushButton.setText(_translate("Form", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
